apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: webserver30-tomcat8-openshift-custom
    name: webserver30-tomcat8-openshift
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift
      from:
        kind: DockerImage
        name: registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: webserver30-tomcat8-openshift-custom
    name: webserver30-tomcat8-openshift-custom
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: webserver30-tomcat8-openshift-custom
    name: webserver30-tomcat8-openshift-custom
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: webserver30-tomcat8-openshift-custom:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/eljeko/ocp-tomcat-custom-image
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: webserver30-tomcat8-openshift:latest
      type: Docker
    triggers:
    - github:
        secret: vEYeeuVNs9hv30CKu60U
      type: GitHub
    - generic:
        secret: _sldqHdSXLqrriPi0cph
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
